### ISSUE TITLE
使用键盘控制组件

### ISSUE THREAD

**Issue by shincurry** [HackPlan/UUI#28]
考虑给一些组件加上键盘按键控制的功能，比如：

* 标签页 Tabs 使用 `←` `→` 切换页面
* 使用 `w` `s` `a` `d` 切换组件之间的 focus 状态
* 使用 `←` `→` `↑` `↓` 切换 Select 和 Cascader 选项

**Comment by wattlebird** [comment]
在考虑给控件增加键盘控制功能时，请务必遵循 ARIA 1.2 规范：https://w3c.github.io/aria-practices/

**Comment by orzFly** [comment]
> 使用 w s a d 切换组件之间的 focus 状态

这个听起来我觉得有点奇怪。有什么其他 UI 控件库支持这样操作吗（显然，游戏除外？）

**Comment by shincurry** [comment]
> > 使用 w s a d 切换组件之间的 focus 状态
> 
> 这个听起来我觉得有点奇怪。有什么其他 UI 控件库支持这样操作吗（显然，游戏除外？）

这只是举个例子，实际上实际不一定会做这个（

**Comment by shincurry** [comment]
主要参考 WAI-ARIA 第三章每个 Widget 的 **Keyboard Interaction** 部分的说明，以及第六章的开发指南。

UUI 对于这个部分的开发工作主要流程：

1. 鉴于 UUI 目前缺少 Accordion，可以先开发一个这样的组件，并且实现 Keyboard Interaction
2. ~~封装一个通用的用于实现 Keyboard Interaction 的工具，这个工具应该要适用于所有的 UUI 组件（也许需要，目前不确定具体的实现细节）~~ 不同 Widget 差异比较大，只能各自实现
3. 将已有的组件根据需要实现 Keyboard Interaction

对于键盘控制功能，在 UI 方面需要完善组件处于 `:focus` `:focus-within` 状态的样式。（像 Button 那样添加border之类的）

https://github.com/HackPlan/UUI/projects/2
