### ISSUE TITLE
Warning: Expected server HTML to contain a matching...

### ISSUE THREAD

**Issue by u-u-z** [HackPlan/UUI#34]
![screenshot](https://i.loli.net/2020/08/20/zkAVNZRWmLTEtJs.png)

When I use **Dialog** components in **Next.js (SSR)**,  I got a **Warning** on the screenshot in the **browser console**.

Server render with client render are inconsistent. After all, it is a warning, hope it can be resolved. :-)

**Comment by shincurry** [comment]
fixed in d11f71b522af06cacf4a012dbf4bab5bc7fb1c61
