### ISSUE TITLE
UUI Components displayed as Anonymous in React Dev Tools

### ISSUE THREAD

**Issue by shincurry** [HackPlan/UUI#5]
UUI components are all displayed as Anonymous when viewed with React Dev Tools.

the nodes inside these components should be given names, which is more convenient for development and debugging.

![截屏2020-06-18 下午12 27 46](https://user-images.githubusercontent.com/4946624/84978454-83d4eb00-b15f-11ea-8e2c-0c01c2f0c7e5.png)

**Comment by hirohe** [comment]
React Dev Tools on my Chrome is version 4.7.0

it shows components name

![image](https://user-images.githubusercontent.com/14357567/84988915-61e66300-b175-11ea-8796-6f2e9e460946.png)

**Comment by shincurry** [comment]
@hirohe fixed this 3 hours ago, forgot to close this issue 😂😂😂😂

https://github.com/HackPlan/UUI/commit/cb67ce78b75652694d3183908af23dd5d7491bdd
