### ISSUE TITLE
文档打不开，检查控制台后有跨域问题

### ISSUE THREAD

**Issue by zz1998022** [HackPlan/UUI#53]
文档打不开，检查控制台后有跨域问题
![image.png](https://i.loli.net/2020/11/11/ntj4Fk2CbMwExvl.png)

**Comment by shincurry** [comment]
Storybook 已有的问题 https://github.com/storybookjs/storybook/issues/7215

这个问题在部分机器和浏览器环境下无法重现，能够正常显示页面 😥

你可以试试更换浏览器或者使用无痕模式浏览
